### PR TITLE
Add initial CITATION.cff

### PR DESCRIPTION
**Pull request by dcslagel**
#### Description:

This pull-request is for Issue #486 "Adding a citation file, and maybe a DOI".  
This change adds an initial CITATION.cff file.  However, I didn't find a DOI so the file does not include a DOI.  
If a DOI is created in the future it can be added to the CITATION.cff at that time.

--
Let me know if this change could be accepted (or rejected) or
needs some additional changes to be approved and merged.

Thank you,
DC

### CODE REVIEW

**Review by kinverarity1 — COMMENTED** [review]
Looks good, but I think the authors should include all contributors, not just me. Is there a standard practice for software citations?

**Comment by dcslagel** [comment]
The following article is what I could find:
https://peerj.com/articles/cs-86/

I read it in the next couple of days.... and have an update.

Also, I did look at several CITATION.cff examples and the tended to have a small a number of authors much like a research-article.

**Comment by dcslagel** [comment]
Update:
I updated the pull request with option 4 in the discussion above since I don't know the family-name and given-name of some of the contributor since they contribute using their GitHub id name and this solution seems like a sensible balance between to include contributions without needing to update this file each time there is a new contributor.

I used the Lasio documentation link to the contributor rather than the GitHub url to contributors, https://github.com/kinverarity1/lasio/graphs/contributors, but both  seem like reasonable options.  Let me know if the GitHub link is preferred and I'll make the change. 

--
Let me know if this change could be accepted (or rejected) or
needs some additional changes to be approved and merged.

Thank you,
DC

**Review by kinverarity1 — APPROVED** [review]
Great! Thank you!

**Pull request merged**
