### PR TITLE
Issue #513 - LAS 3 files

### PR DESCRIPTION
**Pull request by jwildman135**
Regarding Issue #513 
- Here is a selection of real world LAS 3 files that are known to fail on the latest version of LASIO.
- They all load into TechLog fine.
- They are from a variety of companies/countries/providers etc.
- All header data has been anonymized, and data sections have been trimmed down to reduce file size.
- Please feel free to edit/filter down the files

### CODE REVIEW

**Comment by dcslagel** [comment]
This might be a good addition that could encourage progress on enable Lasio to more fully handle LAS 3.0 files.  

It may not be practical,  but if the files are renamed to more closely identify either their Lasio-failure or a specific characteristic of the file it could be helpful to future maintenances....  Is that possible?

**Comment by jwildman135** [comment]
I have renamed the files and added a markdown file for further clarity. There's a few files that have errors upon opening but, the bulk of the issues arise from having the 'Data Section Sets'. This results in sections that you wouldn't necessarily know the keys for, and an empty 'curves' section.

**Comment by dcslagel** [comment]
@jwildman135 ,  This is a nice change.  The additional markdown file is really helpful!

**Comment by kinverarity1** [comment]
Thank you, this is wonderful and very helpful.. ❤️

**Review by kinverarity1 — APPROVED** [review]

**Pull request merged**
