### PR TITLE
Add benchmark test for the speed of reading a LAS file

### PR DESCRIPTION
**Pull request by kinverarity1**
To run it you need to have [`pytest-benchmark`](https://pytest-benchmark.readthedocs.io/) installed, and run the benchmarked test using:

```
$ pytest lasio/tests/test_speed.py
```

To compare two branches, you need to run and store the benchmark from the first branch e.g. master
and then run and compare the benchmark from the second branch. e.g.

```
$ git checkout master
$ mkdir ../lasio-benchmarks
$ pytest tests/test_speed.py --benchmark-autosave --benchmark-storage ../lasio-benchmarks --benchmark-compare
```

For example this compares current `master` to an version where I added `import time; time.sleep(0.5)`:

```
----------------------------------------------------------------------------------------- benchmark: 2 tests -----------------------------------------------------------------------------------------
Name (time in s)                               Min               Max              Mean            StdDev            Median               IQR            Outliers     OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_read_v12_sample_big (0001_d2e0ca0)     1.6540 (1.0)      1.7107 (1.0)      1.6791 (1.0)      0.0222 (1.0)      1.6724 (1.0)      0.0324 (1.0)           2;0  0.5955 (1.0)           5           1
test_read_v12_sample_big (NOW)              2.1621 (1.31)     2.2645 (1.32)     2.2033 (1.31)     0.0377 (1.70)     2.1967 (1.31)     0.0364 (1.12)          2;0  0.4539 (0.76)          5           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

### CODE REVIEW

**Comment by kinverarity1** [comment]
Failing tests only because I didn't add the requirement for pytest-benchmark to Travis CI - I'm going to remove Travis CI though because we don't need it.

**Comment by dcslagel** [comment]
After `mkdir ../lasio-benchmarks` ,  I needed to run the pytest command once, then add `...sleep...` and re-run the pytest cmd to get the comparison output.  Is that what you are doing also?  If so lets update the instructions in the main comment here.

**Comment by kinverarity1** [comment]
Yep go ahead it's not an ideal setup. Should we store the benchmark outputs under version control? Or add a ".benchmarks" folder to .gitignore?

**Comment by dcslagel** [comment]
The benchmark numbers that I get when running `pytest tests/test_speed.py` are slightly different. 
```
--------------------------------------------------- benchmark: 1 tests --------------------------------------------------
Name (time in ms)                 Min       Max      Mean  StdDev    Median     IQR  Outliers     OPS  Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------
test_read_v12_sample_big     942.4416  946.3918  944.5560  1.5469  945.0133  2.2893       2;0  1.0587       5           1
-------------------------------------------------------------------------------------------------------------------------
```
Since this is likely to be the case with everyone's different machines, it probably doesn't make sense to put the benchmark results in version_control.   So I lean toward adding .benchmarks to .gitignore

**Comment by kinverarity1** [comment]
Is that on `master`? My machine is rather low spec. 

OK that makes sense. I'll add to .gitignore and add these pytest commands to the standard pytest arguments so everybody testing locally should see the benchmark come up. Thanks for testing this out!

**Comment by kinverarity1** [comment]
I'd like to somehow include this for GitHub Actions because I suspect my difficulty in the past has been that my machine has some pretty major processor power management stuff going on. If I run code one day it runs obviously slower or faster than another day. But if we run on GH actions, we'd need to store results somewhere, presumably in the repository itself...

**Comment by dcslagel** [comment]
That test_speed.py run was done on the master branch.  So my 942 msec is equivalent to 1650 msec on your machine.

**Comment by dcslagel** [comment]
`test_speed.py is already being run by GH and the results are recorded in the GitHub Actions tab.  So we probably don't need to store the results in the repo.  


Here are the results from a recent run on the master branch:

```
https://github.com/kinverarity1/lasio/actions/runs/758347072

3.8 on ubuntu
----------------------------------------------- benchmark: 1 tests ----------------------------------------------
Name (time in s)                Min     Max    Mean  StdDev  Median     IQR  Outliers     OPS  Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------
test_read_v12_sample_big     1.2218  1.2354  1.2291  0.0048  1.2293  0.0039       2;0  0.8136       5           1
-----------------------------------------------------------------------------------------------------------------
```

**Pull request merged**
