### PR TITLE
after allowing characters in the data section, df() function was retu…

### PR DESCRIPTION
**Pull request by krzysztof-slowinski**
…rning DataFrame with columns of dtype object for all columns if there are characters in the data section - this is a fix by attempting to convert the columns to float64 if they only contain numerical data

### CODE REVIEW

**Comment by kinverarity1** [comment]
Thanks! I am away on some fieldwork at the moment but will try to merge this asap when I get a chance.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by krzysztof-slowinski** [comment]
It is worth to mention that I tried to do the fix in las.py#set_data where the curve.data is assigned (currently at line 623), but fixing it at that location did not result in the change of type in the DataFrame returned through df() due to the way this DataFrame is constructed. If possible, it would be worth to fix it at the origin, which las.py#set_data seems to be, but it would require some additional changes.

**Comment by kinverarity1** [comment]
OK I see what you mean. It'll be a bit messy but I'll add some code in LASFile.set_data_from_df to try and convert each DataFrame column to floats if possible. In addition to your commit.

Thanks!

**Comment by kinverarity1** [comment]
I'll merge this now and work on what I mentioned when possible. Cheers.

**Pull request merged**
