### PR TITLE
Add test case for url/files with mixed line-endings

### PR DESCRIPTION
**Pull request by dcslagel**
The test file for this case is in a temporary location.
It can be moved to kinverarity1/lasio/master in a followup
pull-request.

This is the test case for #359

Let me know if this change could be accepted (or rejected) or
needs some additional changes before being approved and merged.

Thank you,
DC

### CODE REVIEW

**Comment by dcslagel** [comment]
Travis test cases failed.  I'll recheck things tomorrow....

**Comment by kinverarity1** [comment]
No worries, thanks! something funny went wrong with Travis earlier - don't know what it is. Something about a pytest requirement.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dcslagel** [comment]
Looks like the issue is that newer versions on pytest don't yet work with pytest_cov on older python versions.

```
pluggy.manager.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 4.3.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pytest>=4.6'))!
```

**Comment by dcslagel** [comment]
Okay, commit 2d0a75f enables the python 2.7 test to pass, and all tests pass.  
DC

**Comment by kinverarity1** [comment]
Thanks 🦸

**Comment by kinverarity1** [comment]
The code in this PR was released as part of [v0.26](https://github.com/kinverarity1/lasio/releases/tag/v0.26)

**Pull request merged**
