### PR TITLE
Fixing #166

### PR DESCRIPTION
**Pull request by dagrha**
On Ubuntu 17.10 even after #170 I was still getting UnicodeDecodeError on the file referenced on #166, I think because I was specifying neither that `autodetect_encoding=True` nor `encoding='blah-blah'`, like so:

    l = lasio.read('/home/dagrha/Downloads/1045387215_top100ft.txt')

The program was not seeing a BOM but it was also not being told to do autodetect_encoding, so the UnicodeDecodeError was still being raised.

As discussed in https://github.com/kinverarity1/lasio/issues/166#issuecomment-339321558 I've changed the logic a little bit. First, I changed `autodetect_encoding` to be True by default. If chardet is not installed though, then a few common encodings are tried. If that fails, then finally UnicodeDecodeError is raised.

I'm not sure that what I've got here is the best solution, but it is now working for me. I still need to write some tests for this.

I apologize about all those spurious deletions and insertions the my editor put in there.

### CODE REVIEW

**Comment by kinverarity1** [comment]
Thanks for this! I had a look and realised this is still tricky. I think the behaviour of ``autodetect_encoding`` should depend on what the user does with the ``encoding`` argument - otherwise a user might be under the assumption that the encoding they specified is correct, even though lasio found it raised a UnicodeDecodeError, but managed to open it with a different one. If the user has logging off (which 99% will), then they'll never know.

So the simple solution I'm writing up now is to get rid of autodetect_encoding in a backwards-compatible way, and add 'auto', 'chardet', and 'cchardet' options to the encoding argument. Then, whenever a user doesn't specify an actual encoding, lasio tries the common list as you have put in here.

and still feel a bit uncomfortable with the logic that if autodetect_encoding=False, it would still be testing a variety of encodings. i.e. if the user specifies ``read(autodetect_encoding=False, encoding='latin-1')``, has logging off, and the actual encoding is windows-1252, then lasio would have successfully parsed the file as windows-1252 and the user might be under the reasonable assumption that the actual encoding is indeed say latin-1 - even though ``codecs.open(..., encoding='latin-1')`` was raising a UnicodeDecodeError

Anyway I've kept your changes and made some more so that even autodetec

**Comment by kinverarity1** [comment]
Sorry - just realised your PR doesn't lead to the situation I described. Never mind. Thanks!

**Comment by kinverarity1** [comment]
I needed a branch here to push to, so am working on your code in #175  sorry

**Comment by dagrha** [comment]
Ooh, I like your idea about just having an `encoding` argument.

Just as a discussion point, would it make any sense to make `encoding='auto'` the default behavior, i.e. when encoding is not explicitly specified in `read()`? The only reason I ask is that relying on chardet could be safer bet for guessing the correct encoding. Then `adhoc_test_encoding` (i.e. list of common encodings) would only be used if chardet is not installed. Or does relying on chardet by default add too much overhead? 

Either way, fine by me, just wanted to throw that out there!

**Comment by kinverarity1** [comment]
Yep I think that sounds good, i think people prefer error-free posting by default!! I'd just make chardet and maybe cchardet dependencies for lasio. Seems worthwhile.

**Pull request merged**
