### PR TITLE
Rearrange reader

### PR DESCRIPTION
**Pull request by kinverarity1**
This PR will finalise rearranging the reader code so that the following process is followed when reading a file:

- [x] 1. The file is iterated over line by line looking for ~ characters and it stores the location of these in the file and the contents of the line (i.e. the section title). 
- [x] 2. The reader returns to each section. For those which are not data sections it seeks to the beginning of each one and parses it by iterating only over the lines which are in that section
- [x] 3. After all that, the parser returns to each data section and parses it, using the information obtaining from parsing the definition/curves section in step 2

### CODE REVIEW

**Comment by dcslagel** [comment]
Rebase findings:
- I wasn't able to make a rebase branch that you could merge to rearrange-reader and then to master without conflicts.  So not posting a rebase-branch pull-request
- There are just 2 conflicts
   - tests/test_read.py  (Take the master branch changes)
   - tests/test_read_30.py (Take the rearrange-reader changes)
- Reviewing the code after rebasing everything looked okay.
- You should see good post-rebase test-coverage results.  This is what my local post-rebase results are:
220 passed, 3 skipped
```
Name                       Stmts   Miss  Cover
----------------------------------------------
lasio/__init__.py             13      2    85%
lasio/convert_version.py      20     20     0%
lasio/defaults.py             11      0   100%
lasio/examples.py             42     10    76%
lasio/excel.py                88     34    61%
lasio/exceptions.py            6      0   100%
lasio/las.py                 376     55    85%
lasio/las_items.py           190     31    84%
lasio/las_version.py          34     22    35%
lasio/reader.py              437     84    81%
lasio/writer.py              160      9    94%
----------------------------------------------
TOTAL                       1377    267    81%
```

**Comment by dcslagel** [comment]
Just checking on this pull-request.  Is there additional tasks that should be done to enable this to merge?

**Comment by kinverarity1** [comment]
@dcslagel no thanks, all the hard work has been done now!! I just need some time to do it, should be this weekend.

**Comment by dcslagel** [comment]
Okay,  Great. :-)   Yeah, I thought you might be busy but I wanted to check incase there was something we could unblock.  :-)

**Pull request merged**
