### PR TITLE
Remove reader.py:read_file_contents - unused

### PR DESCRIPTION
**Pull request by kinverarity1**
I think as part of #327 I was probably meant to remove the function `reader.py:read_file_contents`. All tests pass without this function, however coverage is not 100% so I want to be sure before removing the code.

@dcslagel you have probably looked more closely over the related changes than I did; does this seem right to you?

### CODE REVIEW

**Comment by dcslagel** [comment]
@kinverarity1,  I have a caution about removing read_file_contents() too quickly also. 

I did the following searches that show Lasio is no-longer calling read_file_contents.
```bash
$ cd lasio
$ grep -rl read_file_contents *
docs/source/lasio.rst
htmlcov/lasio_las_py.html
htmlcov/lasio_debug-reader_py.html
htmlcov/lasio_reader_py.html
lasio/reader.py

$ grep  read_file_contents lasio/reader.py
def read_file_contents(
```

However, In scanning the removing read_file_contents() code, there are some interesting few details we should check whether if they are relevant and if so, exist in the new code.

Could this pull-request be kept around for a while to give us time to read through the code through read through?

Thanks,
DC

**Comment by kinverarity1** [comment]
Yep no hurry 👍

**Comment by dcslagel** [comment]
@kinverarity1, I reviewed reader:read_file_contents() and compared with the current code.  It is okay to proceed with removing reader:read_file_contents().  

Findings:
- https://github.com/kinverarity1/lasio/pull/401  is re-adding a try clause wasn't in the new code but looks like it is still relevant.

**Comment by dcslagel** [comment]
@kinverarity1,

Just checking on this pull-request. I think it is ready to merge, but let me know if it needs changes or is rejected.

Thanks,
DC

**Comment by kinverarity1** [comment]
Thanks @dcslagel

**Pull request merged**
